name = "imdb-top250"
main = "src/index.js"
compatibility_date = "2025-01-01"
# Cloudflare account: Mmdju (workers.dev subdomain: mmdju)
account_id = "525eb5c067d16e8bcb2eab23b20ee7a1"

[[kv_namespaces]]
binding = "CACHE"
id = "50faea9871874ed98ef7cb2f06926c63"

[[d1_databases]]
binding = "DB"
database_name = "imdb-top250-db"
database_id = "70f3a656-da77-43a0-bc99-12d7a042f78f"
migrations_dir = "migrations"
